<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ddad5ba2-d190-4193-a66a-cd2de07fa3a6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TexasMediaDart.Identity.Application\TexasMediaDart.Identity.Application.csproj" />
    <ProjectReference Include="..\TexasMediaDart.Identity.Infrastructure\TexasMediaDart.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
